### ISSUE TITLE
Replace symlink file to the real one

### ISSUE THREAD

**Issue by sumitsharansatsangi** [hemanta212/inventory_app#3]
[itemform](https://github.com/hemanta212/Flutter-Inventory-App/blob/master/lib/app/.%23itemform.dart) and [selling_form](https://github.com/hemanta212/Flutter-Inventory-App/blob/master/lib/app/.%23itemform.dart) are symlink file .

Please replace it with real one.
Thank you

**Comment by hemanta212** [comment]
Those are editor generated temp files mistakenly slipped during commit, the actual files are inside the forms folder
